export const FETCH_CATEGORIES_SAGA = 'FETCH_CATEGORIES_SAGA';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE';
export const FETCH_CATEGORIES_HOOK = 'FETCH_CATEGORIES_HOOK';